image: archlinux
packages:
  - buildah
sources:
  - https://codeberg.org/emersion/soju-containers.git
secrets:
  - 106c7011-4e0e-4b33-a3f2-ffea55ce3f4b # codeberg package registry token
environment:
  images: soju kimchi gamja
tasks:
  - build: |
      cd soju-containers
      for image in $images; do
        buildah build \
          --platform linux/amd64,linux/arm64,linux/arm/v6 \
          --target $image \
          --manifest codeberg.org/emersion/$image \
          --build-arg-file argfile.conf \
          $image
      done
  - deploy: |
      cd soju-containers
      [ "$(git rev-parse HEAD)" = "$(git rev-parse origin/master)" ] || complete-build
      buildah login codeberg.org --username emersion --password-stdin <~/codeberg-token.txt
      for image in $images; do
        buildah manifest push codeberg.org/emersion/$image

        ref=$(awk -F = -v image="$image" '$1 == toupper(image "_REF") { print $2 }' argfile.conf)
        if [ "$ref" != "" ] && [ "$ref" != master ]; then
          buildah manifest push codeberg.org/emersion/$image docker://codeberg.org/emersion/$image:$ref
        fi
      done
