image: archlinux
packages:
  - podman
sources:
  - https://codeberg.org/emersion/soju-containers.git
secrets:
  - 106c7011-4e0e-4b33-a3f2-ffea55ce3f4b # codeberg package registry token
environment:
  SOJU_REF: v0.8.2
tasks:
  - build: |
      cd soju-containers
      platforms=linux/amd64,linux/arm64
      podman build --platform $platforms --target soju --manifest soju --build-arg SOJU_REF=$SOJU_REF .
      podman build --platform $platforms --target gamja --manifest gamja .
  - deploy: |
      cd soju-containers
      [ "$(git rev-parse HEAD)" = "$(git rev-parse origin/master)" ] || complete-build
      podman login codeberg.org --username emersion --password-stdin <~/codeberg-token.txt
      podman manifest push soju codeberg.org/emersion/soju:$SOJU_REF
      podman manifest push soju codeberg.org/emersion/soju:latest
      podman manifest push gamja codeberg.org/emersion/gamja
