name: soju

configs:
  soju:
    file: soju/config
  gamja:
    file: gamja/config.json

volumes:
  db:

services:
  soju:
    image: codeberg.org/emersion/soju
    build:
      context: soju
    ports:
      - "127.0.0.1:6667:6667"
    configs:
      - source: soju
        target: /soju-config
    volumes:
      - "db:/db"
    networks:
      default:
        aliases:
          - gamja-backend
  gamja:
    image: codeberg.org/emersion/gamja
    build:
      context: gamja
    configs:
      - source: gamja
        target: /gamja-config.json
    ports:
      - "127.0.0.1:8080:80"
