name: soju

configs:
  soju:
    file: soju-config

volumes:
  db:

services:
  soju:
    image: codeberg.org/emersion/soju
    build:
      target: soju
    ports:
      - "127.0.0.1:6667:6667"
    configs:
      - source: soju
        target: /soju-config
    volumes:
      - "db:/db"
  gamja:
    image: codeberg.org/emersion/gamja
    build:
      target: gamja
    ports:
      - "127.0.0.1:8080:80"
